version: '2'

services:
  psqldb:
    image: postgres
    ports:
      - "8005:5432"
    volumes:
      - ../psqldb:/var/lib/postgresql/data
  neo4jdb:
    image: neo4j
    ports:
     - "8003:7474"
     - "8004:7687"
    volumes:
       - ../neo4jdb/data:/data
       - ../neo4jdb/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/neo4jpass
  webfront:
    build: ../webfront
    image: webfront
    command: ./docker-entrypoint.sh
    volumes:
      - ../webfront:/webfront
    depends_on:
      - psqldb
      - neo4jdb
  proxyserver:
    build: ../proxyserver
    image: proxyserver
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - ../proxyserver:/proxyserver
  authserver:
    build: ../authserver
    image: authserver
    command: ./docker-entrypoint.sh
    volumes:
      - ../authserver:/authserver
  taskservice:
    build: ../taskservice
    image: taskservice
    command: ./docker-entrypoint.sh
    ports:
      - "8002:8000"
    volumes:
      - ../taskservice:/taskservice
