version: '2'

services:
  psqldb:
    image: postgres
    ports:
      - "8005:5432"
    volumes:
      - ../psqldb:/var/lib/postgresql/data
  neo4jdb:
    image: neo4j
    ports:
     - "8003:7474"
     - "8004:7687"
    volumes:
       - ../neo4jdb/data:/data
       - ../neo4jdb/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/neo4jpass
  memcached:
    image: memcached
  # nginx-proxy:
  #   build: ../nginx-proxy
  #   image: nginx-proxy
  #   command: sh docker-entrypoint.sh
  #   ports:
  #     - "8010:80"
  #   volumes:
  #     - ../nginx-proxy:/etc/nginx/conf.d
  proxyserver:
    build: ../proxyserver
    image: proxyserver
    command: ./docker-entrypoint.sh
    ports:
      - "8001:8000"
    volumes:
      - ../proxyserver:/proxyserver
    environment:
      - DJANGO_SETTINGS_MODULE=proxyserver.settings.dev
    depends_on:
      - psqldb
      - neo4jdb
      - memcached
  webfront:
    build: ../webfront
    image: webfront
    command: ./docker-entrypoint.sh
    volumes:
      - ../webfront:/webfront
    environment:
      - DJANGO_SETTINGS_MODULE=webfront.settings.dev
    depends_on:
      - proxyserver
  webmain:
    build: ../webmain
    image: webmain
    command: ./docker-entrypoint.sh
    volumes:
      - ../webmain:/webmain
    ports:
      - "8006:3000"
    environment:
      - BASE_URL=http://localhost:8001/api/v1
    depends_on:
      - proxyserver
  authserver:
    build: ../authserver
    image: authserver
    command: ./docker-entrypoint.sh
    volumes:
      - ../authserver:/authserver
    depends_on:
      - proxyserver
    environment:
      - DJANGO_SETTINGS_MODULE=authserver.settings.dev
  taskservice:
    build: ../taskservice
    image: taskservice
    command: ./docker-entrypoint.sh
    ports:
      - "8002:8000"
    volumes:
      - ../taskservice:/taskservice
    environment:
      - DJANGO_SETTINGS_MODULE=taskservice.settings.dev
    depends_on:
      - proxyserver
